name: Deploy Bicep Template to Azure

on:
  push:
    branches:
      - main  # Trigger the deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1
      
      # Log in to Azure using Service Principal
      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      
      # Set Azure Subscription
      - name: Set Azure subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy Bicep file to Azure
      - name: Deploy Bicep template
        run: |
          az deployment sub create --location EastUS --template-file ./path/to/azureresources.bicep
